
import { supabase } from '../lib/supabase';
import { Candidate, Status } from '../types';

export const candidateService = {
    async getAll() {
        const { data, error } = await supabase
            .from('candidates')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        // Map snake_case DB to camelCase frontend types if needed, 
        // but better to keep consistency or transform here.
        // For this implementation, we'll assume we map it or the frontend adapts.
        // Let's map it for safety to match the 'types.ts' interface.

        return data.map(mapToCandidate);
    },

    async getById(id: string) {
        const { data, error } = await supabase
            .from('candidates')
            .select('*')
            .eq('id', id)
            .single();

        if (error) throw error;
        return mapToCandidate(data);
    },

    async create(candidate: Omit<Candidate, 'id' | 'createdAt' | 'addedAt' | 'fitScore' | 'status'>) {
        // We treat 'addedAt' as 'created_at' generated by DB.
        // Status defaults to 'Applied'.
        const { data, error } = await supabase
            .from('candidates')
            .insert([{
                name: candidate.name,
                email: candidate.email,
                phone: candidate.phone,
                role: candidate.role,
                skills: candidate.skills,
                experience: candidate.experience,
                linkedin: candidate.linkedIn,
                location: candidate.location,
                // Default fitScore to 0 until calculated
            }])
            .select()
            .single();

        if (error) throw error;
        return mapToCandidate(data);
    },

    async delete(id: string) {
        const { error } = await supabase
            .from('candidates')
            .delete()
            .eq('id', id);

        if (error) throw error;
    },

    async update(id: string, updates: Partial<Candidate>) {
        const dbUpdates: any = {};
        if (updates.name) dbUpdates.name = updates.name;
        if (updates.email) dbUpdates.email = updates.email;
        if (updates.phone) dbUpdates.phone = updates.phone;
        if (updates.role) dbUpdates.role = updates.role;
        if (updates.skills) dbUpdates.skills = updates.skills;
        if (updates.experience) dbUpdates.experience = updates.experience;
        if (updates.linkedIn) dbUpdates.linkedin = updates.linkedIn;
        if (updates.location) dbUpdates.location = updates.location;

        const { data, error } = await supabase
            .from('candidates')
            .update(dbUpdates)
            .eq('id', id)
            .select()
            .single();

        if (error) throw error;
        return mapToCandidate(data);
    },

    // Placeholder for search - simply returns all for now unless we implement full text search
    // Real implementation would call an edge function for embedding search
    async search(query: string) {
        // For now, simple ILIKE search on name or skills
        const { data, error } = await supabase
            .from('candidates')
            .select('*')
            .or(`name.ilike.%${query}%,role.ilike.%${query}%`)
            .order('created_at', { ascending: false });

        if (error) throw error;
        return data.map(mapToCandidate);
    }
};

// Helper: Map DB snake_case to Frontend camelCase
function mapToCandidate(row: any): Candidate {
    return {
        id: row.id,
        name: row.name,
        email: row.email,
        phone: row.phone,
        role: row.role,
        skills: row.skills, // JSONB comes back as array
        experience: row.experience,
        status: 'Applied', // Base candidates don't have status, job_candidates do. 
        // But the UI type Candidate has status. We might need to fetch this contextually.
        // For the main table list, we might default to 'Applied' or fetch latest status?
        // The PRD implies Candidates in the pool vs Candidates in a Job.
        // Let's default to 'Applied' or generic status for now.
        fitScore: 0, // Calculated dynamically in context of a job or search
        addedAt: row.created_at,
        linkedIn: row.linkedin,
        location: row.location
    };
}
