
import { supabase } from '../lib/supabase';
import { Candidate, Status } from '../types';
import { generateEmbedding, vectorSearchCandidates } from './searchService';

export const candidateService = {
    async getAll() {
        const { data, error } = await supabase
            .from('candidates')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) throw error;

        // Map snake_case DB to camelCase frontend types if needed, 
        // but better to keep consistency or transform here.
        // For this implementation, we'll assume we map it or the frontend adapts.
        // Let's map it for safety to match the 'types.ts' interface.

        return data.map(mapToCandidate);
    },

    async getById(id: string) {
        const { data, error } = await supabase
            .from('candidates')
            .select('*')
            .eq('id', id)
            .single();

        if (error) throw error;
        return mapToCandidate(data);
    },

    async create(candidate: Omit<Candidate, 'id' | 'createdAt' | 'addedAt' | 'fitScore'>) {
        // We treat 'addedAt' as 'created_at' generated by DB.
        // Status defaults to 'Applied'.

        // Generate embedding for semantic search
        // Combine name, role, skills, and resume text for embedding
        const embeddingText = [
            candidate.name,
            candidate.role || '',
            candidate.skills?.join(', ') || '',
            candidate.location || '',
            candidate.resumeText || '',
        ].filter(Boolean).join(' ');

        let embedding: number[] | null = null;
        try {
            embedding = await generateEmbedding(embeddingText);
        } catch (error) {
            console.warn('Failed to generate embedding for candidate, continuing without it:', error);
            // Continue without embedding - it can be generated later
        }

        const insertData: any = {
            name: candidate.name,
            email: candidate.email,
            phone: candidate.phone,
            role: candidate.role,
            skills: candidate.skills,
            experience: candidate.experience,
            linkedin: candidate.linkedIn,
            location: candidate.location,
            resume_url: candidate.resumeUrl,
            resume_text: candidate.resumeText,
            status: candidate.status || 'New',
        };

        if (embedding) {
            insertData.embedding = `[${embedding.join(',')}]`;
        }

        const { data, error } = await supabase
            .from('candidates')
            .insert([insertData])
            .select()
            .single();

        if (error) throw error;
        return mapToCandidate(data);
    },

    async delete(id: string) {
        const { error } = await supabase
            .from('candidates')
            .delete()
            .eq('id', id);

        if (error) throw error;
    },

    async update(id: string, updates: Partial<Candidate>) {
        const dbUpdates: any = {};
        if (updates.name) dbUpdates.name = updates.name;
        if (updates.email) dbUpdates.email = updates.email;
        if (updates.phone) dbUpdates.phone = updates.phone;
        if (updates.role) dbUpdates.role = updates.role;
        if (updates.skills) dbUpdates.skills = updates.skills;
        if (updates.experience) dbUpdates.experience = updates.experience;
        if (updates.linkedIn) dbUpdates.linkedin = updates.linkedIn;
        if (updates.location) dbUpdates.location = updates.location;
        if (updates.resumeUrl) dbUpdates.resume_url = updates.resumeUrl;
        if (updates.resumeText) dbUpdates.resume_text = updates.resumeText;
        if (updates.status) dbUpdates.status = updates.status;

        // Regenerate embedding if any searchable fields changed
        const searchableFieldsChanged = updates.name || updates.role || updates.skills || updates.location || updates.resumeText;
        if (searchableFieldsChanged) {
            // Fetch current candidate to get all fields for embedding
            const { data: current } = await supabase
                .from('candidates')
                .select('*')
                .eq('id', id)
                .single();

            if (current) {
                const updatedCandidate = { ...current, ...dbUpdates };
                const embeddingText = [
                    updatedCandidate.name,
                    updatedCandidate.role || '',
                    Array.isArray(updatedCandidate.skills) ? updatedCandidate.skills.join(', ') : '',
                    updatedCandidate.location || '',
                    updatedCandidate.resume_text || '',
                ].filter(Boolean).join(' ');

                try {
                    const embedding = await generateEmbedding(embeddingText);
                    dbUpdates.embedding = `[${embedding.join(',')}]`;
                } catch (error) {
                    console.warn('Failed to regenerate embedding:', error);
                }
            }
        }

        const { data, error } = await supabase
            .from('candidates')
            .update(dbUpdates)
            .eq('id', id)
            .select()
            .single();

        if (error) throw error;
        return mapToCandidate(data);
    },

    // Semantic search using vector embeddings
    async search(query: string): Promise<Candidate[]> {
        if (!query || query.trim().length === 0) {
            // If empty query, return all candidates
            return this.getAll();
        }

        try {
            // Use vector search for semantic matching
            const results = await vectorSearchCandidates(query.trim(), 50);

            // Map results to Candidate format with similarity as fitScore
            return results.map(({ candidate, similarity }) => {
                const mapped = mapToCandidate(candidate);
                // Convert similarity (0-1) to fitScore (0-100)
                mapped.fitScore = Math.round(similarity * 100);
                return mapped;
            });
        } catch (error) {
            console.error('Vector search failed, falling back to text search:', error);

            // Fallback to text-based search if vector search fails
            const { data, error: textError } = await supabase
                .from('candidates')
                .select('*')
                .or(`name.ilike.%${query}%,role.ilike.%${query}%`)
                .order('created_at', { ascending: false });

            if (textError) throw textError;
            return data.map(mapToCandidate);
        }
    },

    async generateMissingEmbeddings() {
        const { data: candidates, error } = await supabase
            .from('candidates')
            .select('*')
            .is('embedding', null);

        if (error) {
            console.error('Error fetching candidates with missing embeddings:', error);
            return;
        }

        if (!candidates || candidates.length === 0) return;

        console.log(`Found ${candidates.length} candidates with missing embeddings. Regenerating...`);

        for (const candidate of candidates) {
            const embeddingText = [
                candidate.name,
                candidate.role || '',
                Array.isArray(candidate.skills) ? candidate.skills.join(', ') : '',
                candidate.location || '',
                candidate.experience || '',
                candidate.resume_text || ''
            ].filter(Boolean).join(' ');

            try {
                const embedding = await generateEmbedding(embeddingText);
                // Format as string for vector type update
                const embeddingString = `[${embedding.join(',')}]`;

                const { error: updateError } = await supabase
                    .from('candidates')
                    .update({ embedding: embeddingString } as any)
                    .eq('id', candidate.id);

                if (updateError) throw updateError;
                console.log(`Regenerated embedding for candidate: ${candidate.name} (${candidate.id})`);
            } catch (err) {
                console.error(`Failed to regenerate embedding for candidate ${candidate.id}:`, err);
            }
        }
    },

    async uploadResume(file: File) {
        const fileExt = file.name.split('.').pop();
        const fileName = `${Math.random().toString(36).substring(2, 15)}_${Date.now()}.${fileExt}`;
        const filePath = `${fileName}`;

        const { error: uploadError } = await supabase.storage
            .from('resumes')
            .upload(filePath, file);

        if (uploadError) {
            console.error('Upload error:', uploadError);
            throw uploadError;
        }

        const { data } = supabase.storage.from('resumes').getPublicUrl(filePath);
        return data.publicUrl;
    },

    async parseResume(fileUrl: string) {
        // In a real scenario, this calls the n8n webhook
        const N8N_WEBHOOK_URL = import.meta.env.VITE_N8N_WEBHOOK_URL;

        if (!N8N_WEBHOOK_URL) {
            console.warn('VITE_N8N_WEBHOOK_URL is not set. Simulating parsing.');
            return new Promise<{ name: string, email: string, skills: string[], role: string, experience: string }>((resolve) => {
                setTimeout(() => {
                    resolve({
                        name: "Alex Morgan",
                        email: "alex.morgan@example.com",
                        role: "Senior Frontend Engineer",
                        experience: "5",
                        skills: ["React", "TypeScript", "Node.js"]
                    });
                }, 2000);
            });
        }

        try {
            const response = await fetch(N8N_WEBHOOK_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ fileUrl })
            });

            if (!response.ok) throw new Error('Failed to parse resume via n8n');
            return await response.json();
        } catch (error) {
            console.error('Parsing error:', error);
            throw error;
        }
    }
};

// Helper: Map DB snake_case to Frontend camelCase
function mapToCandidate(row: any): Candidate {
    return {
        id: row.id,
        name: row.name,
        email: row.email,
        phone: row.phone,
        role: row.role,
        skills: row.skills, // JSONB comes back as array
        experience: row.experience,
        status: row.status || 'New',
        // But the UI type Candidate has status. We might need to fetch this contextually.
        // For the main table list, we might default to 'New' or fetch latest status?
        // The PRD implies Candidates in the pool vs Candidates in a Job.
        // Let's default to 'New' or generic status for now.
        fitScore: 0, // Calculated dynamically in context of a job or search
        addedAt: row.created_at,
        updatedAt: row.updated_at,
        linkedIn: row.linkedin,
        location: row.location,
        resumeUrl: row.resume_url,
        resumeText: row.resume_text,
    };
}
